# Generated by Django 3.1.3 on 2021-03-13 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authenticate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=264)),
                ('author', models.CharField(max_length=30)),
                ('message', models.TextField(verbose_name='Message')),
            ],
        ),
    ]
