# Generated by Django 3.1.3 on 2021-03-13 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_authenticate', '0003_suggestions_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suggestions',
        ),
    ]
