# Generated by Django 3.1.1 on 2020-12-06 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0002_auto_20201206_2026'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pro_lang',
            new_name='Prolang',
        ),
    ]
