# Generated by Django 3.1.1 on 2020-12-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0003_auto_20201206_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='prolang',
            name='myfile',
            field=models.FileField(default='', upload_to='mypdf/'),
            preserve_default=False,
        ),
    ]
