# Generated by Django 3.1.3 on 2020-12-10 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0004_prolang_myfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=264)),
                ('author', models.CharField(max_length=30)),
                ('mainimage', models.ImageField(upload_to='pic_upload', verbose_name='Put Image file')),
                ('pdf', models.FileField(upload_to='pdf_upload', verbose_name='Put PDF file')),
                ('preview_text', models.TextField(verbose_name='Preview Text')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('category_img', models.ImageField(upload_to='pic_upload', verbose_name='Put Category Image file')),
                ('describe', models.TextField(verbose_name='Description Text')),
            ],
        ),
        migrations.DeleteModel(
            name='Prolang',
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='ebook.category'),
        ),
    ]
