# Generated by Django 3.1.3 on 2021-03-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0005_auto_20201210_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='audio',
            field=models.FileField(default='', upload_to='musics/', verbose_name='Put Audio file'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
