# Generated by Django 3.1.3 on 2021-03-02 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0006_auto_20210303_0139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='audio',
        ),
    ]
