# Generated by Django 3.1.3 on 2021-03-14 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0008_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
